# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_auto_20191201_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(default='Default', max_length=144),
            preserve_default=False,
        ),
    ]
