# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_group_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hospital_contact',
            field=models.PositiveIntegerField(default=911),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='police_contact',
            field=models.PositiveIntegerField(default=911),
            preserve_default=False,
        ),
    ]
